version: '3'
services:
  web:
    build: .
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: 6
      POSTGRES_PASSWORD: dibimbing
    ports:
      - "5439:5432"